#ifdef EXTERN_CG_CVAR
#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags, description ) extern vmCvar_t vmCvar;
#endif

#ifdef DECLARE_CG_CVAR
#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags, description ) vmCvar_t vmCvar;
#endif

#ifdef CG_CVAR_LIST
#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags, description ) { &vmCvar, cvarName, defaultString, cvarFlags, description },
#endif

CG_CVAR( cg_ignore, "cg_ignore", "0", 0, NULL ) // used for debugging
CG_CVAR( cg_autoswitch, "cg_autoswitch", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawGun, "cg_drawGun", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_zoomFov, "cg_zoomfov", "22.5", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_fov, "cg_fov", "110", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_viewsize, "cg_viewsize", "100", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_shadows, "cg_shadows", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_gibs, "cg_gibs", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_draw2D, "cg_draw2D", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawStatus, "cg_drawStatus", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawTimer, "cg_drawTimer", "4", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawFPS, "cg_drawFPS", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawSnapshot, "cg_drawSnapshot", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_draw3dIcons, "cg_draw3dIcons", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawIcons, "cg_drawIcons", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawAmmoWarning, "cg_drawAmmoWarning", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawAttacker, "cg_drawAttacker", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawSpeed, "cg_drawSpeed", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawCrosshair, "cg_drawCrosshair", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawCrosshairNames, "cg_drawCrosshairNames", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawRewards, "cg_drawRewards", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairSize, "cg_crosshairSize", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairHealth, "cg_crosshairHealth", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairX, "cg_crosshairX", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairY, "cg_crosshairY", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_brassTime, "cg_brassTime", "2500", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_simpleItems, "cg_simpleItems", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_addMarks, "cg_marks", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_lagometer, "cg_lagometer", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_railTrailTime, "cg_railTrailTime", "400", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_gun_frame, "cg_gun_frame", "", CVAR_ROM, NULL )
CG_CVAR( cg_gun_x, "cg_gunX", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_gun_y, "cg_gunY", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_gun_z, "cg_gunZ", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_centertime, "cg_centertime", "3", CVAR_CHEAT, NULL )
CG_CVAR( cg_runpitch, "cg_runpitch", "0.002", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_runroll, "cg_runroll", "0.005", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_bobup, "cg_bobup", "0.005", CVAR_CHEAT, NULL )
CG_CVAR( cg_bobpitch, "cg_bobpitch", "0.0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_bobroll, "cg_bobroll", "0.0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_swingSpeed, "cg_swingSpeed", "0.3", CVAR_CHEAT, NULL )
CG_CVAR( cg_animSpeed, "cg_animspeed", "1", CVAR_CHEAT, NULL )
CG_CVAR( cg_debugAnim, "cg_debuganim", "0", CVAR_CHEAT, NULL )
CG_CVAR( cg_debugPosition, "cg_debugposition", "0", CVAR_CHEAT, NULL )
CG_CVAR( cg_debugEvents, "cg_debugevents", "0", CVAR_CHEAT, NULL )
CG_CVAR( cg_errorDecay, "cg_errordecay", "100", 0, NULL )
CG_CVAR( cg_nopredict, "cg_nopredict", "0", 0, NULL )
CG_CVAR( cg_noPlayerAnims, "cg_noplayeranims", "0", CVAR_CHEAT, NULL )
CG_CVAR( cg_showmiss, "cg_showmiss", "0", 0, NULL )
CG_CVAR( cg_footsteps, "cg_footsteps", "1", CVAR_CHEAT, NULL )
CG_CVAR( cg_tracerChance, "cg_tracerchance", "0.4", CVAR_CHEAT, NULL )
CG_CVAR( cg_tracerWidth, "cg_tracerwidth", "1", CVAR_CHEAT, NULL )
CG_CVAR( cg_tracerLength, "cg_tracerlength", "100", CVAR_CHEAT, NULL )
CG_CVAR( cg_thirdPersonRange, "cg_thirdPersonRange", "40", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_thirdPersonAngle, "cg_thirdPersonAngle", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_thirdPersonOffset, "cg_thirdPersonOffset", "25", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_thirdPerson, "cg_thirdPerson", "0", 0, NULL )
CG_CVAR( cg_teamChatTime, "cg_teamChatTime", "3000", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamChatHeight, "cg_teamChatHeight", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_forceModel, "cg_forceModel", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_predictItems, "cg_predictItems", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_deferPlayers, "cg_deferPlayers", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawTeamOverlay, "cg_drawTeamOverlay", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamOverlayUserinfo, "teamoverlay", "0", CVAR_ROM | CVAR_USERINFO, NULL )
CG_CVAR( cg_stats, "cg_stats", "0", 0, NULL )
CG_CVAR( cg_drawFriend, "cg_drawFriend", "2", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamChatsOnly, "cg_teamChatsOnly", "0", CVAR_ARCHIVE, NULL )
// the following variables are created in other parts of the system,
// but we also reference them here
CG_CVAR( cg_buildScript, "com_buildScript", "0", 0, NULL ) // force loading of all possible data amd error on failures
CG_CVAR( cg_paused, "cl_paused", "0", CVAR_ROM, NULL )
CG_CVAR( cg_blood, "com_blood", "2", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_alwaysWeaponBar, "cg_alwaysWeaponBar", "1", CVAR_ARCHIVE, NULL ) //Elimination
CG_CVAR( cg_hitsound, "cg_hitsound", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_voteflags, "cg_voteflags", "*", CVAR_ROM, NULL )
CG_CVAR( cg_cyclegrapple, "cg_cyclegrapple", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_vote_custom_commands, "cg_vote_custom_commands", "", CVAR_ROM, NULL )
CG_CVAR( cg_synchronousClients, "g_synchronousClients", "0", CVAR_SYSTEMINFO, NULL ) // communicated by systeminfo

CG_CVAR( cg_autovertex, "cg_autovertex", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_enableDust, "g_enableDust", "0", CVAR_SERVERINFO, NULL )
CG_CVAR( cg_enableBreath, "g_enableBreath", "0", CVAR_SERVERINFO, NULL )
CG_CVAR( cg_obeliskRespawnDelay, "g_obeliskRespawnDelay", "10", CVAR_SERVERINFO, NULL )

CG_CVAR( cg_cameraOrbit, "cg_cameraOrbit", "0", CVAR_CHEAT, NULL )
CG_CVAR( cg_cameraOrbitDelay, "cg_cameraOrbitDelay", "50", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_timescaleFadeEnd, "cg_timescaleFadeEnd", "1", 0, NULL )
CG_CVAR( cg_timescaleFadeSpeed, "cg_timescaleFadeSpeed", "0", 0, NULL )
CG_CVAR( cg_timescale, "timescale", "1", 0, NULL )
CG_CVAR( cg_scorePlum, "cg_scorePlums", "0", CVAR_USERINFO | CVAR_ARCHIVE, NULL )
CG_CVAR( cg_obituaryOutput, "cg_obituaryOutput", "3", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_cameraMode, "com_cameraMode", "0", CVAR_CHEAT, NULL )

CG_CVAR( pmove_fixed, "pmove_fixed", "0", CVAR_SYSTEMINFO, NULL )
CG_CVAR( pmove_msec, "pmove_msec", "8", CVAR_SYSTEMINFO, NULL )
CG_CVAR( pmove_float, "pmove_float", "1", CVAR_SYSTEMINFO, NULL )
CG_CVAR( cg_noTaunt, "cg_noTaunt", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_noProjectileTrail, "cg_noProjectileTrail", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_smallFont, "ui_smallFont", "0.25", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_bigFont, "ui_bigFont", "0.4", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_oldRail, "cg_oldRail", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_oldRocket, "cg_oldRocket", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_leiEnhancement, "cg_leiEnhancement", "0", CVAR_ARCHIVE, NULL )             // LEILEI default off (in case of wiener)
CG_CVAR( cg_leiGoreNoise, "cg_leiGoreNoise", "0", CVAR_ARCHIVE, NULL )                 // LEILEI
CG_CVAR( cg_leiBrassNoise, "cg_leiBrassNoise", "1", CVAR_ARCHIVE, NULL )               // LEILEI
CG_CVAR( cg_leiSuperGoreyAwesome, "cg_leiSuperGoreyAwesome", "0", CVAR_ARCHIVE, NULL ) // LEILEI
CG_CVAR( cg_oldPlasma, "cg_oldPlasma", "1", CVAR_ARCHIVE, NULL )
//unlagged - client options
CG_CVAR( cg_delag, "cg_delag", "1", CVAR_ARCHIVE | CVAR_USERINFO, NULL )
CG_CVAR( cg_cmdTimeNudge, "cg_cmdTimeNudge", "0", CVAR_ARCHIVE | CVAR_USERINFO, NULL )
// this will be automagically copied from the server
CG_CVAR( sv_fps, "sv_fps", "40", CVAR_SYSTEMINFO, NULL )
CG_CVAR( cg_projectileNudge, "cg_projectileNudge", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_optimizePrediction, "cg_optimizePrediction", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cl_timeNudge, "cl_timeNudge", "0", CVAR_ARCHIVE, NULL )
//unlagged - client options
CG_CVAR( cg_trueLightning, "cg_trueLightning", "0.9", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_music, "cg_music", "", CVAR_ARCHIVE, NULL )

CG_CVAR( cg_fragmsgsize, "cg_fragmsgsize", "0.75", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairPulse, "cg_crosshairPulse", "0", CVAR_ARCHIVE, NULL )

CG_CVAR( cg_differentCrosshairs, "cg_differentCrosshairs", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch1, "cg_ch1", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch1size, "cg_ch1size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch2, "cg_ch2", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch2size, "cg_ch2size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch3, "cg_ch3", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch3size, "cg_ch3size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch4, "cg_ch4", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch4size, "cg_ch4size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch5, "cg_ch5", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch5size, "cg_ch5size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch6, "cg_ch6", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch6size, "cg_ch6size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch7, "cg_ch7", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch7size, "cg_ch7size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch8, "cg_ch8", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch8size, "cg_ch8size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch9, "cg_ch9", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch9size, "cg_ch9size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch10, "cg_ch10", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch10size, "cg_ch10size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch11, "cg_ch11", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch11size, "cg_ch11size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch12, "cg_ch12", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch12size, "cg_ch12size", "24", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch13, "cg_ch13", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_ch13size, "cg_ch13size", "24", CVAR_ARCHIVE, NULL )

CG_CVAR( cg_crosshairColorRed, "cg_crosshairColorRed", "1.0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairColorGreen, "cg_crosshairColorGreen", "1.0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_crosshairColorBlue, "cg_crosshairColorBlue", "1.0", CVAR_ARCHIVE, NULL )

CG_CVAR( cg_weaponBarStyle, "cg_weaponBarStyle", "8", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_weaponOrder, "cg_weaponOrder", "/1/2/4/3/6/7/8/9/5/", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_chatBeep, "cg_chatBeep", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamChatBeep, "cg_teamChatBeep", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_developer, "developer", "0", CVAR_CHEAT, NULL )

//OmegA
CG_CVAR( cg_ambient, "cg_ambient", "1", CVAR_ARCHIVE | CVAR_LATCH, NULL )
CG_CVAR( cg_bobgun, "cg_bobgun", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_brightPlayers, "cg_brightPlayers", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_damagePlums, "cg_damagePlums", "1", CVAR_USERINFO | CVAR_ARCHIVE, NULL )
CG_CVAR( cg_deadColor, "cg_deadColor", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_draw3DCrosshairNames, "cg_draw3DCrosshairNames", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawEmotes, "cg_drawEmotes", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawEnemy, "cg_drawEnemy", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawFriendSkulls, "cg_friendSkulls", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawFriendThroughWalls, "cg_friendThroughWalls", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawItemPickup, "cg_drawItemPickup", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawOldScoreboard, "cg_drawOldScoreboard", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawSmallHealthSphere, "cg_drawSmallHealthSphere", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawTeamBackground, "cg_drawTeamBackground", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_drawThirdPersonCrosshair, "cg_drawThirdPersonCrosshair", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_enemyColor, "cg_enemyColor", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_enemyModel, "cg_enemyModel", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_enemySounds, "cg_enemySounds", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_flagStyle, "cg_flagStyle", "2", CVAR_ARCHIVE | CVAR_LATCH, NULL )
CG_CVAR( cg_forceTeamSkins, "cg_forceTeamSkins", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_hitmarker, "cg_hitmarker", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_killsound, "cg_killsound", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_omegaInitialized, "cg_omegaInitialized", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_predictAmmo, "cg_predictAmmo", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_screenshake, "cg_screenshake", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_selfSounds, "cg_selfSounds", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_showSpawns, "cg_showSpawns", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_shotgunSparks, "cg_shotgunSparks", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_showSpecZoom, "cg_showSpecZoom", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_smoothBodySink, "cg_smoothBodySink", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_switchCycle, "cg_switchCycle", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamColor, "cg_teamColor", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamModel, "cg_teamModel", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_teamSounds, "cg_teamSounds", "", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_thinLightningBolt, "cg_thinLightningBolt", "0", CVAR_ARCHIVE | CVAR_LATCH, NULL )
CG_CVAR( cg_thirdPersonFlagSprite, "cg_thirdPersonFlagSprite", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_timerHeight, "cg_timerHeight", "25", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_timerWidth, "cg_timerWidth", "25", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_timerX, "cg_timerX", "318", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_timerY, "cg_timerY", "2", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_transparentGun, "cg_transparentGun", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_wallhack, "cg_wallhack", "0", CVAR_ARCHIVE | CVAR_CHEAT, NULL )
CG_CVAR( cg_zoomAnim, "cg_zoomAnim", "1", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_zoomAnimSpeed, "cg_zoomAnimSpeed", "2", CVAR_ARCHIVE, NULL )
CG_CVAR( cg_zoomToggle, "cg_zoomToggle", "0", CVAR_ARCHIVE, NULL )
CG_CVAR( com_maxfps, "com_maxfps", "250", CVAR_ARCHIVE, NULL )
CG_CVAR( pmove_aircontrol, "pmove_aircontrol", "0", CVAR_SYSTEMINFO, NULL )
CG_CVAR( pmove_autohop, "pmove_autohop", "0", CVAR_SYSTEMINFO, NULL )
CG_CVAR( pmove_doublejump, "pmove_doublejump", "0", CVAR_SYSTEMINFO, NULL )
CG_CVAR( pmove_overbounce, "pmove_overbounce", "0", CVAR_SYSTEMINFO, NULL )

#undef CG_CVAR
